My_birthday=input("Enter your birthday:")
Mom_birthday=input("Enter your mom's birthday:")
Dad_birthday=input("Enter your dad's birthday:")
Siblings_birthday=input("Enter your siblings birthday:")
Grandma_birthday=input("Enter your grandma's birthday:")
print("My birthday is on",My_birthday)
print("My mom's birthday is on", Mom_birthday)
print("My dad's birthday is on", Dad_birthday)
print("My sibling's birthday is on", Siblings_birthday)
print("My grandma's birthday is on", Grandma_birthday)
print("These Are The Best Birthday's To Have!")